### ISSUE TITLE
Allow to use the `thumb` switch for unisim-armsec

### ISSUE THREAD

**Issue by J08nY** [binsec/Rel#1]
Currently, the value `arm` is hardcoded as the CLI argument to the `unisim-armsec` external decoder at:
https://github.com/binsec/Rel/blob/master/src/disasm/arm/armToDba.ml#L225

Passing `thumb` instead lets one disassemble and work with more ARM binaries. This could be also done in base binsec (and other repositories where the same disasm code lives) and propagated into the rel_bench repository as a CLI option for its `run.py`.

**Comment by Lesly-Ann** [comment]
Thanks a lot for reporting this possibility of improvement.
I won't have time to fix it now in this repository but I forwarded you suggestion to other Binsec developers.
