### ISSUE TITLE
Unable to make switch due to merlin dependency contraint

### ISSUE THREAD

**Issue by JoaoDDuarte** [binsec/Rel#5]
As I mentioned in my pull request [here](https://github.com/binsec/Rel/pull/3):

> Merlin currently has a constraint issue on the yojson dependency (see https://github.com/ocaml/merlin/issues/1478), which means that installing merlin will always fail, and hence, so will this package. This means that binsec/rel is currently uninstallable (at least without using the docker image).

> Until that is solved, I manually added the yojson<2.0.0 dependency and the installation now works.

**Comment by Lesly-Ann** [comment]
Solved by cb07f9be2fce94d0e87cbb3f5273d9eb4f46cd37
